version: "3"

services:
  mongodb-service:
    image: "mongo"
    hostname: "mongodb"
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - "mongodata:/data/db" 
    ports:
      - 27017:27017

  rest-wasps:
    container_name: rest-wasps
    build: rest/wasps/.
    ports:
      - 19081:19081
    depends_on:
      - mongodb-service
    restart: unless-stopped

volumes:
  mongodata:


